'use strict';const crypto=require('node:crypto');
class PgPaymentProviderWorker{constructor({pool,secretResolver,paystack,sellerEvents,maxAttempts=6}){Object.assign(this,{pool,secretResolver,paystack,sellerEvents,maxAttempts})}
 async claimNext(){const token=crypto.randomUUID(),c=await this.pool.connect();try{await c.query('BEGIN');const j=(await c.query(`SELECT id FROM payment_provider_outbox WHERE status='pending' AND available_at<=now() AND (lease_until IS NULL OR lease_until<=now()) ORDER BY available_at,created_at,id LIMIT 1 FOR UPDATE SKIP LOCKED`)).rows[0];if(!j){await c.query('COMMIT');return null}const r=(await c.query(`UPDATE payment_provider_outbox SET attempts=attempts+1,lease_until=now()+interval '60 seconds',worker_token=$2,last_error=NULL WHERE id=$1 RETURNING *`,[j.id,token])).rows[0];await c.query('COMMIT');return r}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release()}}
 async processNext(){const j=await this.claimNext();if(!j)return{outcome:'idle'};try{const i=(await this.pool.query(`SELECT p.*,r.live_session_id,c.secret_ref,c.callback_url FROM payment_intents p JOIN reservations r ON r.id=p.reservation_id AND r.merchant_id=p.merchant_id JOIN payment_provider_connections c ON c.merchant_id=p.merchant_id AND c.provider='paystack' AND c.status='active' WHERE p.id=$1 AND p.merchant_id=$2`,[j.payment_intent_id,j.merchant_id])).rows[0];if(!i)throw Object.assign(new Error('payment intent/provider connection missing'),{retryable:false});
 if(['pending','settled','reconciliation_required'].includes(i.status)){await this.done(j,{outcome:'already_initialized'});return{outcome:'completed'}}
 const ref=`FD-${String(i.id).replaceAll('-','').slice(0,24)}-${j.attempts}-${crypto.randomBytes(5).toString('hex')}`;
 // Critical ordering: persist every attempted reference BEFORE the external call.
 await this.pool.query(`INSERT INTO payment_provider_references(id,merchant_id,payment_intent_id,provider,reference,state) VALUES(gen_random_uuid(),$1,$2,'paystack',$3,'attempting')`,[j.merchant_id,i.id,ref]);
 const secret=await this.secretResolver.resolve(i.secret_ref);let out;try{out=await this.paystack.initialize({secretKey:secret,email:i.customer_email,amountMinor:Number(i.amount_minor),currency:i.currency,reference:ref,callbackUrl:i.callback_url,metadata:{flowdesk_payment_intent_id:i.id,flowdesk_reservation_id:i.reservation_id}})}catch(e){await this.pool.query(`UPDATE payment_provider_references SET state=$2,updated_at=now() WHERE merchant_id=$1 AND reference=$3`,[j.merchant_id,e.retryable?'superseded':'failed',ref]);throw e}
 await this.pool.query(`UPDATE payment_intents SET status='pending',authorization_url=$3,access_code=$4,initialized_at=now(),last_provider_error=NULL,updated_at=now() WHERE id=$1 AND merchant_id=$2 AND status='initializing'`,[i.id,j.merchant_id,out.authorizationUrl,out.accessCode]);await this.pool.query(`UPDATE payment_provider_references SET state=CASE WHEN reference=$2 THEN 'active' ELSE 'superseded' END,updated_at=now() WHERE payment_intent_id=$1`,[i.id,ref]);
 await this.sellerEvents.emit({merchantId:j.merchant_id,sourceType:'payment_provider_outbox',sourceId:j.id,eventType:'payment.checkout_ready',liveSessionId:i.live_session_id,payload:{paymentIntentId:i.id,reservationId:i.reservation_id,authorizationUrl:out.authorizationUrl}});
 await this.done(j,{outcome:'ready',paymentIntentId:i.id});return{outcome:'completed'}}catch(e){const terminal=e.retryable===false||j.attempts>=this.maxAttempts,delay=Math.min(300000,1000*2**Math.max(0,j.attempts-1));const q=await this.pool.query(terminal?`UPDATE payment_provider_outbox SET status='dead_letter',lease_until=NULL,worker_token=NULL,last_error=$3 WHERE id=$1 AND worker_token=$2`:`UPDATE payment_provider_outbox SET available_at=now()+($3::bigint*interval '1 millisecond'),lease_until=NULL,worker_token=NULL,last_error=$4 WHERE id=$1 AND worker_token=$2`,terminal?[j.id,j.worker_token,String(e.message).slice(0,2000)]:[j.id,j.worker_token,delay,String(e.message).slice(0,2000)]);return{outcome:q.rowCount===1?(terminal?'dead_letter':'retry_scheduled'):'lease_lost'}}}
 async done(j,result){await this.pool.query(`UPDATE payment_provider_outbox SET status='completed',completed_at=now(),lease_until=NULL,worker_token=NULL,result_body=$3::jsonb WHERE id=$1 AND worker_token=$2`,[j.id,j.worker_token,JSON.stringify(result)])}}
module.exports={PgPaymentProviderWorker};
