'use strict';
const crypto=require('node:crypto');const {normalizePaystackEvent}=require('../providers/paystack');const {normalizeWhatsAppEvent}=require('../providers/whatsapp');const {isRetryableProcessingError,safeError,ProviderPayloadError}=require('../providers/errors');
class PgWebhookInboxWorker{constructor({pool,paymentIntents,whatsappIntents,lifecycle,sellerEvents,maxAttempts=8,leaseSeconds=60,random=Math.random}){Object.assign(this,{pool,paymentIntents,whatsappIntents,lifecycle,sellerEvents,maxAttempts,leaseSeconds,random})}
 backoff(a){return Math.min(300000,Math.max(250,Math.floor(1000*(2**Math.max(0,a-1))*(0.5+this.random()))))}
 async claimNext(){const token=crypto.randomUUID(),c=await this.pool.connect();try{await c.query('BEGIN');const j=(await c.query(`SELECT id FROM webhook_inbox WHERE (status='received' AND next_attempt_at<=now()) OR (status='processing' AND lease_until<=now()) ORDER BY next_attempt_at,received_at,id LIMIT 1 FOR UPDATE SKIP LOCKED`)).rows[0];if(!j){await c.query('COMMIT');return null}
 const out=(await c.query(`UPDATE webhook_inbox SET status='processing',attempts=attempts+1,worker_token=$2,lease_until=now()+make_interval(secs=>$3),last_error=NULL WHERE id=$1 RETURNING *`,[j.id,token,this.leaseSeconds])).rows[0];await c.query('COMMIT');return out}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release()}}
 async markProcessed(j,r){const q=await this.pool.query(`UPDATE webhook_inbox SET status='processed',processed_at=now(),lease_until=NULL,worker_token=NULL,result_body=$3::jsonb,last_error=NULL WHERE id=$1 AND status='processing' AND worker_token=$2`,[j.id,j.worker_token,JSON.stringify(r)]);if(q.rowCount!==1){const e=new Error('lease lost');e.code='WEBHOOK_LEASE_LOST';e.status=503;throw e}}
 async markFailure(j,e){const terminal=!isRetryableProcessingError(e)||j.attempts>=this.maxAttempts;if(terminal){const q=await this.pool.query(`UPDATE webhook_inbox SET status='dead_letter',dead_lettered_at=now(),lease_until=NULL,worker_token=NULL,last_error=$3 WHERE id=$1 AND status='processing' AND worker_token=$2`,[j.id,j.worker_token,safeError(e)]);return{outcome:q.rowCount===1?'dead_letter':'lease_lost'}}
 const delayMs=this.backoff(j.attempts);const q=await this.pool.query(`UPDATE webhook_inbox SET status='received',next_attempt_at=now()+($3::bigint*interval '1 millisecond'),lease_until=NULL,worker_token=NULL,last_error=$4 WHERE id=$1 AND status='processing' AND worker_token=$2`,[j.id,j.worker_token,delayMs,safeError(e)]);return{outcome:q.rowCount===1?'retry_scheduled':'lease_lost',delayMs}}
 async processJob(j){if(j.provider==='paystack'){const n=normalizePaystackEvent(j.payload);if(n.kind==='ignored')return n;const pi=await this.paymentIntents.resolveSuccessfulCharge({merchantId:j.merchant_id,providerReference:n.providerReference,amountMinor:n.amountMinor,currency:n.currency});const r=await this.lifecycle.settlePayment({merchantId:j.merchant_id,reservationId:pi.reservationId,provider:'paystack',providerTransactionId:n.providerTransactionId,amountMinor:n.amountMinor,currency:n.currency});await this.paymentIntents.applySettlementResult({merchantId:j.merchant_id,paymentIntentId:pi.id,result:r});await this.sellerEvents.emitFromWebhook({merchantId:j.merchant_id,inboxId:j.id,eventType:'payment.settled',payload:{reservationId:pi.reservationId,outcome:r.outcome}});return{provider:'paystack',outcome:r.outcome}}
 if(j.provider==='meta_whatsapp'){const n=normalizeWhatsAppEvent(j.payload),r=await this.whatsappIntents.processNormalized({merchantId:j.merchant_id,inboxId:j.id,event:n});if(r.outcome!=='ignored')await this.sellerEvents.emitFromWebhook({merchantId:j.merchant_id,inboxId:j.id,liveSessionId:r.sessionId||null,eventType:r.outcome==='review_required'?'buyer_intent.review_required':r.outcome==='reserved'?'reservation.created':'waitlist.joined',payload:r});return{provider:'meta_whatsapp',outcome:r.outcome}}throw new ProviderPayloadError('WEBHOOK_PROVIDER_UNSUPPORTED','provider unsupported')}
 async processNext(){const j=await this.claimNext();if(!j)return{outcome:'idle'};try{const r=await this.processJob(j);await this.markProcessed(j,r);return{outcome:'processed',jobId:j.id,result:r}}catch(e){return{...await this.markFailure(j,e),jobId:j.id,errorCode:e.code||'UNKNOWN'}}}}
module.exports={PgWebhookInboxWorker};
