'use strict'; const test=require('node:test'); const assert=require('node:assert/strict'); const {StockFreshnessGuard,StockFreshnessError}=require('../src/stock-freshness.guard');
function setup(){let now=1000000;const g=new StockFreshnessGuard({clock:()=>now});g.setRealtimeConnected(true);return {g,advance:n=>now+=n};}
test('offline invalidates and blocks',()=>{const {g}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:3,inventoryVersion:7});g.setNetworkOnline(false);assert.equal(g.getState().reason,'offline');assert.throws(()=>g.assertCanPromise({sessionId:'s',inventoryVariantId:'sku'}),e=>e.code==='STOCK_NOT_FRESH');});
test('reconnect requires new snapshot',()=>{const {g}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:1,inventoryVersion:7});g.setRealtimeConnected(false);assert.equal(g.onReconnect(),1);assert.equal(g.getState().reason,'refresh_required');});
test('superseded generation rejected',()=>{const {g}=setup();g.setRealtimeConnected(false);g.onReconnect();assert.throws(()=>g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:1,inventoryVersion:8,generation:0}),e=>e.code==='STALE_CONNECTION_GENERATION');});
test('expired snapshot blocks online client',()=>{const {g,advance}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:2,inventoryVersion:9});advance(16000);assert.equal(g.getState().reason,'snapshot_expired');});
test('expired ack blocks promise',()=>{const {g,advance}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:2,inventoryVersion:9});advance(11000);assert.equal(g.getState().reason,'server_ack_expired');});
test('fresh stock emits version headers',()=>{const {g}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:2,inventoryVersion:11});assert.deepEqual(g.buildMutationHeaders({sessionId:'s',inventoryVariantId:'sku',quantity:2}),{'If-Inventory-Version':'11','X-FlowDesk-Connection-Generation':'0'});});
test('scope mismatch blocked',()=>{const {g}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'a',availableQty:2,inventoryVersion:11});assert.throws(()=>g.assertCanPromise({sessionId:'s',inventoryVariantId:'b'}),e=>e.code==='SNAPSHOT_SCOPE_MISMATCH');});
test('quantity cannot exceed fresh availability',()=>{const {g}=setup();g.applyAuthoritativeSnapshot({sessionId:'s',inventoryVariantId:'sku',availableQty:1,inventoryVersion:11});assert.throws(()=>g.assertCanPromise({sessionId:'s',inventoryVariantId:'sku',quantity:2}),e=>e.code==='INSUFFICIENT_DISPLAYED_STOCK');});
