'use strict';
class StockFreshnessError extends Error { constructor(code,message,details={}){super(message);this.name='StockFreshnessError';this.code=code;this.status=409;this.details=details;} }
class StockFreshnessGuard {
 constructor({maxSnapshotAgeMs=15000,maxAckAgeMs=10000,clock=()=>Date.now()}={}){if(maxSnapshotAgeMs<=0||maxAckAgeMs<=0)throw new TypeError('freshness windows must be > 0');this.maxSnapshotAgeMs=maxSnapshotAgeMs;this.maxAckAgeMs=maxAckAgeMs;this.clock=clock;this.online=true;this.connected=false;this.snapshot=null;this.lastServerAckAt=null;this.generation=0;}
 setNetworkOnline(v){this.online=!!v;if(!this.online)this._invalidate();}
 setRealtimeConnected(v){this.connected=!!v;if(!this.connected)this._invalidate();}
 recordServerAck({at=this.clock(),generation=this.generation}={}){if(!this.online||!this.connected||generation!==this.generation)return false;this.lastServerAckAt=Number(at);return true;}
 applyAuthoritativeSnapshot({sessionId,inventoryVariantId,availableQty,inventoryVersion,serverObservedAt=this.clock(),generation=this.generation}){if(!this.online||!this.connected)throw new StockFreshnessError('UNTRUSTED_TRANSPORT','Cannot mark stock fresh while transport is unavailable');if(generation!==this.generation)throw new StockFreshnessError('STALE_CONNECTION_GENERATION','Snapshot belongs to a superseded connection');if(!sessionId||!inventoryVariantId||!Number.isInteger(availableQty)||availableQty<0||inventoryVersion==null)throw new TypeError('invalid authoritative stock snapshot');this.snapshot=Object.freeze({sessionId,inventoryVariantId,availableQty,inventoryVersion,serverObservedAt:Number(serverObservedAt),generation});this.lastServerAckAt=this.clock();return this.snapshot;}
 onReconnect(){this.generation+=1;this.connected=true;this.snapshot=null;this.lastServerAckAt=null;return this.generation;}
 getState(){const now=this.clock(),snapshotAgeMs=this.snapshot?Math.max(0,now-this.snapshot.serverObservedAt):null,ackAgeMs=this.lastServerAckAt==null?null:Math.max(0,now-this.lastServerAckAt);let reason=null;if(!this.online)reason='offline';else if(!this.connected)reason='realtime_disconnected';else if(!this.snapshot)reason='refresh_required';else if(snapshotAgeMs>this.maxSnapshotAgeMs)reason='snapshot_expired';else if(ackAgeMs==null||ackAgeMs>this.maxAckAgeMs)reason='server_ack_expired';return Object.freeze({online:this.online,connected:this.connected,generation:this.generation,fresh:reason===null,reason,snapshotAgeMs,ackAgeMs,snapshot:this.snapshot,canPromiseStock:reason===null,displayMode:reason===null?'authoritative':'stale'});}
 assertCanPromise({sessionId,inventoryVariantId,quantity=1}={}){const s=this.getState();if(!s.fresh)throw new StockFreshnessError('STOCK_NOT_FRESH','Refresh and server acknowledgement required before promising stock',{reason:s.reason});if(s.snapshot.sessionId!==sessionId||s.snapshot.inventoryVariantId!==inventoryVariantId)throw new StockFreshnessError('SNAPSHOT_SCOPE_MISMATCH','Snapshot does not match session and variant');if(!Number.isInteger(quantity)||quantity<=0)throw new TypeError('quantity must be positive');if(s.snapshot.availableQty<quantity)throw new StockFreshnessError('INSUFFICIENT_DISPLAYED_STOCK','Fresh snapshot does not show enough stock');return Object.freeze({inventoryVersion:s.snapshot.inventoryVersion,generation:s.generation,observedAvailableQty:s.snapshot.availableQty});}
 buildMutationHeaders(scope){const p=this.assertCanPromise(scope);return Object.freeze({'If-Inventory-Version':String(p.inventoryVersion),'X-FlowDesk-Connection-Generation':String(p.generation)});}
 _invalidate(){this.snapshot=null;this.lastServerAckAt=null;}
}
module.exports={StockFreshnessGuard,StockFreshnessError};
