'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {PgReservationVariantService}=require('../src/reservation.variant.pg');
function scripted(responses){const calls=[];let i=0;const client={query:async(sql,args=[])=>{calls.push({sql:String(sql).replace(/\s+/g,' ').trim(),args});const r=responses[i++];if(r instanceof Error)throw r;if(typeof r==='function')return r({sql,args,calls,index:i-1});return r||{rowCount:0,rows:[]};},release:()=>calls.push({sql:'RELEASE',args:[]})};return{pool:{connect:async()=>client},calls};}
const input={merchantId:'m',reservationId:'r1',destinationInventoryVariantId:'sku-b',idempotencyKey:'0123456789abcdef',actorType:'buyer',actorId:'buyer-1',reason:'Buyer selected another size'};

test('C11 invalid switch input fails before DB access',async()=>{let connected=false;const svc=new PgReservationVariantService({pool:{connect:async()=>{connected=true}}});await assert.rejects(()=>svc.switchVariant({...input,destinationInventoryVariantId:null}),e=>e.code==='INVALID_INPUT');assert.equal(connected,false);});

test('C11 unavailable destination leaves original reservation and inventory untouched',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'r1',live_session_id:'s1',inventory_variant_id:'sku-a',buyer_id:'buyer-1',quantity:2,status:'active'}]}, {rows:[{id:'s1',status:'live'}]}, {rows:[{id:'sku-a',available_qty:0,reserved_qty:2,version:'4'},{id:'sku-b',available_qty:1,reserved_qty:0,version:'7'}]}, {}]);const svc=new PgReservationVariantService({pool:s.pool});await assert.rejects(()=>svc.switchVariant(input),e=>e.code==='DESTINATION_VARIANT_UNAVAILABLE');assert.equal(s.calls.some(x=>/UPDATE reservations SET inventory_variant_id/.test(x.sql)),false);assert.equal(s.calls.some(x=>/INSERT INTO audit_events/.test(x.sql)),false);assert.equal(s.calls.some(x=>/INSERT INTO lifecycle_outbox/.test(x.sql)),false);assert.ok(s.calls.some(x=>x.sql==='ROLLBACK'));});

test('C11 successful switch locks both inventory rows in deterministic order and commits source release + destination claim atomically',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'r1',live_session_id:'s1',inventory_variant_id:'sku-a',buyer_id:'buyer-1',quantity:2,status:'active'}]}, {rows:[{id:'s1',status:'live'}]}, {rows:[{id:'sku-a',available_qty:0,reserved_qty:2,version:'4'},{id:'sku-b',available_qty:3,reserved_qty:0,version:'7'}]}, {rowCount:1,rows:[{version:'5'}]}, {rowCount:1,rows:[{version:'8'}]}, {rows:[{id:'r1',live_session_id:'s1',inventory_variant_id:'sku-b',buyer_id:'buyer-1',quantity:2,status:'active',expires_at:'2099-01-01T00:00:00Z'}]}, {rows:[{id:'audit-1'}]}, {rowCount:1,rows:[{id:'job-1'}]}, {rowCount:1}, {}]);const svc=new PgReservationVariantService({pool:s.pool});const out=await svc.switchVariant(input);assert.equal(out.outcome,'switched');assert.equal(out.promotionQueued,true);assert.equal(out.sourceInventoryVersion,5);assert.equal(out.destinationInventoryVersion,8);const lock=s.calls.find(x=>/FROM inventory_variants/.test(x.sql)&&/FOR UPDATE/.test(x.sql));assert.match(lock.sql,/ORDER BY id FOR UPDATE/);const release=s.calls.findIndex(x=>/available_qty=available_qty\+\$1/.test(x.sql));const claim=s.calls.findIndex(x=>/available_qty=available_qty-\$1/.test(x.sql));const resUpdate=s.calls.findIndex(x=>/UPDATE reservations SET inventory_variant_id/.test(x.sql));const outbox=s.calls.findIndex(x=>/INSERT INTO lifecycle_outbox/.test(x.sql));const commit=s.calls.findIndex(x=>x.sql==='COMMIT');assert.ok(release>0&&claim>release&&resUpdate>claim&&outbox>resUpdate&&outbox<commit);const outboxCall=s.calls[outbox];assert.equal(outboxCall.args[1],'variant_switch');assert.equal(outboxCall.args[2],'audit-1');});

test('C11 source accounting mismatch rolls back before destination claim',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'r1',live_session_id:'s1',inventory_variant_id:'sku-a',buyer_id:'buyer-1',quantity:2,status:'active'}]}, {rows:[{id:'s1',status:'live'}]}, {rows:[{id:'sku-a',available_qty:0,reserved_qty:2,version:'4'},{id:'sku-b',available_qty:3,reserved_qty:0,version:'7'}]}, {rowCount:0,rows:[]}, {}]);const svc=new PgReservationVariantService({pool:s.pool});await assert.rejects(()=>svc.switchVariant(input),e=>e.code==='INVENTORY_ACCOUNTING_CONFLICT');assert.equal(s.calls.filter(x=>/available_qty=available_qty-\$1/.test(x.sql)).length,0);assert.ok(s.calls.some(x=>x.sql==='ROLLBACK'));});

test('C11 same destination is an idempotent no-op with no inventory mutation',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'r1',live_session_id:'s1',inventory_variant_id:'sku-b',buyer_id:'buyer-1',quantity:2,status:'active'}]}, {rowCount:1}, {}]);const svc=new PgReservationVariantService({pool:s.pool});const out=await svc.switchVariant(input);assert.equal(out.outcome,'no_change');assert.equal(s.calls.some(x=>/FROM inventory_variants/.test(x.sql)),false);assert.equal(s.calls.some(x=>/INSERT INTO audit_events/.test(x.sql)),false);});
