'use strict';
function registerControlPlaneRoutes(app,{services,guards}){const auth=guards.authenticate,uuid={type:'string',format:'uuid'};
 app.route({method:'GET',url:'/v1/live-sessions/:sessionId/offers',preHandler:[auth,guards.requirePermission('live_session.manage')],handler:async(r,p)=>p.send({items:await services.offers.list({merchantId:r.auth.merchantId,sessionId:r.params.sessionId})})});
 app.route({method:'PUT',url:'/v1/live-sessions/:sessionId/offers/:alias',schema:{body:{type:'object',required:['inventory_variant_id'],additionalProperties:false,properties:{inventory_variant_id:uuid}}},preHandler:[auth,guards.requirePermission('live_session.manage')],handler:async(r,p)=>p.send(await services.offers.upsert({merchantId:r.auth.merchantId,sessionId:r.params.sessionId,alias:r.params.alias,inventoryVariantId:r.body.inventory_variant_id}))});
 app.route({method:'DELETE',url:'/v1/live-sessions/:sessionId/offers/:alias',preHandler:[auth,guards.requirePermission('live_session.manage')],handler:async(r,p)=>p.send(await services.offers.disable({merchantId:r.auth.merchantId,sessionId:r.params.sessionId,alias:r.params.alias}))});
 app.route({method:'GET',url:'/v1/operations/buyer-intents/review',preHandler:[auth,guards.requirePermission('buyer_intent.review')],handler:async(r,p)=>p.send({items:await services.intentReviews.list({merchantId:r.auth.merchantId,limit:Math.min(100,Math.max(1,Number(r.query.limit||50)))})})});
 app.route({method:'POST',url:'/v1/operations/buyer-intents/review/:reviewId/resolve',schema:{body:{type:'object',required:['session_id','inventory_variant_id','quantity'],additionalProperties:false,properties:{session_id:uuid,inventory_variant_id:uuid,quantity:{type:'integer',minimum:1,maximum:1000}}}},preHandler:[auth,guards.requirePermission('buyer_intent.review')],handler:async(r,p)=>p.send(await services.intentReviews.resolve({merchantId:r.auth.merchantId,reviewId:r.params.reviewId,sessionId:r.body.session_id,inventoryVariantId:r.body.inventory_variant_id,quantity:r.body.quantity,actorId:r.auth.actorId}))});
 app.route({method:'POST',url:'/v1/operations/buyer-intents/review/:reviewId/dismiss',schema:{body:{type:'object',required:['reason'],additionalProperties:false,properties:{reason:{type:'string',minLength:8,maxLength:500}}}},preHandler:[auth,guards.requirePermission('buyer_intent.review')],handler:async(r,p)=>p.send(await services.intentReviews.dismiss({merchantId:r.auth.merchantId,reviewId:r.params.reviewId,actorId:r.auth.actorId,reason:r.body.reason}))});
 app.route({method:'GET',url:'/v1/operations/webhooks/health',preHandler:[auth,guards.requirePermission('webhook.health.read')],handler:async(r,p)=>p.send(await services.webhookHealth.getHealth({merchantId:r.auth.merchantId}))});}
module.exports={registerControlPlaneRoutes};
