'use strict';const {stableHash}=require('../../../transaction-core/src/reservation.pg');
class CheckoutError extends Error{constructor(code,message,status=409){super(message);Object.assign(this,{code,status})}}
class PgPaymentCheckoutService{constructor({pool}){this.pool=pool}
 async create({merchantId,reservationId,customerEmail,idempotencyKey}){const email=String(customerEmail||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new CheckoutError('CUSTOMER_EMAIL_INVALID','valid email required',400);
 const hash=stableHash({reservationId,customerEmail:email}),c=await this.pool.connect();try{await c.query('BEGIN');const ins=await c.query(`INSERT INTO idempotency_requests(merchant_id,idempotency_key,request_hash,operation,expires_at) VALUES($1,$2,$3,'create_payment_checkout',now()+interval '24 hours') ON CONFLICT(merchant_id,idempotency_key) DO NOTHING RETURNING merchant_id`,[merchantId,idempotencyKey,hash]);
 if(!ins.rowCount){const prior=(await c.query(`SELECT request_hash,response_body FROM idempotency_requests WHERE merchant_id=$1 AND idempotency_key=$2 FOR UPDATE`,[merchantId,idempotencyKey])).rows[0];if(prior?.request_hash!==hash)throw new CheckoutError('IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD','idempotency key conflict');if(!prior?.response_body)throw new CheckoutError('IDEMPOTENCY_REQUEST_IN_PROGRESS','checkout request in progress');await c.query('COMMIT');return{...prior.response_body,deduplicated:true}}
 const r=(await c.query(`SELECT r.id,r.quantity,r.status,r.expires_at,i.unit_price_minor,i.currency FROM reservations r JOIN inventory_variants i ON i.id=r.inventory_variant_id AND i.merchant_id=r.merchant_id WHERE r.id=$1 AND r.merchant_id=$2 FOR UPDATE OF r`,[reservationId,merchantId])).rows[0];if(!r)throw new CheckoutError('RESERVATION_NOT_FOUND','reservation not found',404);if(!['active','payment_pending'].includes(r.status))throw new CheckoutError('RESERVATION_NOT_PAYABLE','reservation not payable');const now=(await c.query('SELECT now() db_now')).rows[0].db_now;if(new Date(r.expires_at)<=new Date(now))throw new CheckoutError('RESERVATION_EXPIRED','reservation expired');
 const unit=Number(r.unit_price_minor),qty=Number(r.quantity);if(!Number.isSafeInteger(unit)||unit<1||!/^[A-Z]{3}$/.test(r.currency||''))throw new CheckoutError('PRICE_NOT_CONFIGURED','authoritative price not configured');const amount=unit*qty;if(!Number.isSafeInteger(amount))throw new CheckoutError('PAYMENT_AMOUNT_OVERFLOW','payment amount unsafe',500);
 let pi=(await c.query(`SELECT id,status,authorization_url,access_code FROM payment_intents WHERE merchant_id=$1 AND reservation_id=$2 AND status IN('initializing','pending','settled','reconciliation_required') ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[merchantId,reservationId])).rows[0];
 if(!pi){pi=(await c.query(`INSERT INTO payment_intents(id,merchant_id,reservation_id,provider,amount_minor,currency,status,customer_email) VALUES(gen_random_uuid(),$1,$2,'paystack',$3,$4,'initializing',$5) RETURNING id,status,authorization_url,access_code`,[merchantId,reservationId,amount,r.currency,email])).rows[0];await c.query(`UPDATE reservations SET status='payment_pending',updated_at=now() WHERE id=$1 AND merchant_id=$2 AND status='active'`,[reservationId,merchantId])}
 if(pi.status==='initializing')await c.query(`INSERT INTO payment_provider_outbox(id,merchant_id,payment_intent_id,operation) VALUES(gen_random_uuid(),$1,$2,'initialize_paystack_checkout') ON CONFLICT(payment_intent_id,operation) DO NOTHING`,[merchantId,pi.id]);
 const result={outcome:pi.status==='pending'?'ready':'initializing',paymentIntentId:pi.id,reservationId,amountMinor:amount,currency:r.currency,authorizationUrl:pi.authorization_url||null,accessCode:pi.access_code||null};await c.query(`UPDATE idempotency_requests SET response_status=$3,response_body=$4::jsonb WHERE merchant_id=$1 AND idempotency_key=$2`,[merchantId,idempotencyKey,result.outcome==='ready'?200:202,JSON.stringify(result)]);await c.query('COMMIT');return result}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release()}}
 async get({merchantId,paymentIntentId}){const r=(await this.pool.query(`SELECT id,reservation_id,amount_minor,currency,status,authorization_url,access_code,initialized_at FROM payment_intents WHERE id=$1 AND merchant_id=$2`,[paymentIntentId,merchantId])).rows[0];if(!r)throw new CheckoutError('PAYMENT_INTENT_NOT_FOUND','payment intent not found',404);return{paymentIntentId:r.id,reservationId:r.reservation_id,amountMinor:Number(r.amount_minor),currency:r.currency,status:r.status,authorizationUrl:r.authorization_url||null,accessCode:r.access_code||null,initializedAt:r.initialized_at||null}}}
module.exports={PgPaymentCheckoutService,CheckoutError};
