'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {PgReservationOverrideService}=require('../src/reservation.override.pg');
function scripted(responses){const calls=[];let i=0;const client={query:async(sql,args=[])=>{calls.push({sql:String(sql).replace(/\s+/g,' ').trim(),args});const r=responses[i++];if(r instanceof Error)throw r;return r||{rowCount:0,rows:[]};},release:()=>calls.push({sql:'RELEASE',args:[]})};return{pool:{connect:async()=>client},calls};}
const base={merchantId:'m',sessionId:'s',inventoryVariantId:'sku',buyerId:'b',quantity:1,idempotencyKey:'0123456789abcdef',actorId:'op',permissions:['reservation.force_allocate'],stepUpVerifiedAt:'2026-09-29T22:00:00Z',reason:'Buyer verified at counter',expectedInventoryVersion:4};

test('C08 rejects missing permission before DB access',async()=>{let connected=false;const svc=new PgReservationOverrideService({pool:{connect:async()=>{connected=true}},clock:()=>new Date('2026-09-29T22:05:00Z')});await assert.rejects(()=>svc.forceAllocate({...base,permissions:[]}),(e)=>e.code==='OVERRIDE_PERMISSION_REQUIRED');assert.equal(connected,false);});
test('C08 rejects expired step-up before DB access',async()=>{let connected=false;const svc=new PgReservationOverrideService({pool:{connect:async()=>{connected=true}},clock:()=>new Date('2026-09-29T22:20:01Z')});await assert.rejects(()=>svc.forceAllocate(base),(e)=>e.code==='STEP_UP_REQUIRED');assert.equal(connected,false);});
test('C09 privileged stock mutation requires an expected inventory version before DB access',async()=>{let connected=false;const svc=new PgReservationOverrideService({pool:{connect:async()=>{connected=true}},clock:()=>new Date('2026-09-29T22:05:00Z')});await assert.rejects(()=>svc.forceAllocate({...base,expectedInventoryVersion:undefined}),(e)=>e.code==='INVENTORY_VERSION_REQUIRED'&&e.status===428);assert.equal(connected,false);});
test('C09 stale inventory version fails after row lock and before mutation',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'s',status:'live',reservation_ttl_seconds:300}]}, {rows:[{id:'sku',available_qty:2,reserved_qty:0,version:'5'}]}, {}]);const svc=new PgReservationOverrideService({pool:s.pool,clock:()=>new Date('2026-09-29T22:05:00Z')});await assert.rejects(()=>svc.forceAllocate(base),(e)=>e.code==='STALE_INVENTORY_VERSION');assert.ok(s.calls.some(x=>/FROM inventory_variants .* FOR UPDATE/.test(x.sql)));assert.equal(s.calls.some(x=>/INSERT INTO reservations/.test(x.sql)),false);assert.equal(s.calls.some(x=>/INSERT INTO audit_events/.test(x.sql)),false);assert.ok(s.calls.some(x=>x.sql==='ROLLBACK'));});
test('C08 force allocation rechecks authoritative stock and never permits negative inventory',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'s',status:'live',reservation_ttl_seconds:300}]}, {rows:[{id:'sku',available_qty:0,reserved_qty:0,version:'4'}]}, {}]);const svc=new PgReservationOverrideService({pool:s.pool,clock:()=>new Date('2026-09-29T22:05:00Z')});await assert.rejects(()=>svc.forceAllocate(base),(e)=>e.code==='OVERRIDE_STOCK_RECHECK_FAILED');assert.equal(s.calls.some(x=>/INSERT INTO reservations/.test(x.sql)),false);assert.ok(s.calls.some(x=>x.sql==='ROLLBACK'));});
test('C08 successful override reserves and audits in same transaction before commit',async()=>{const s=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'s',status:'live',reservation_ttl_seconds:300}]}, {rows:[{id:'sku',available_qty:2,reserved_qty:0,version:'4'}]}, {rows:[{id:'r1',status:'active',expires_at:'2099-01-01T00:00:00Z',quantity:1}]}, {rowCount:1,rows:[{version:'5'}]}, {rowCount:1}, {rowCount:1}, {}]);const svc=new PgReservationOverrideService({pool:s.pool,clock:()=>new Date('2026-09-29T22:05:00Z')});const out=await svc.forceAllocate(base);assert.equal(out.override,true);const audit=s.calls.findIndex(x=>/INSERT INTO audit_events/.test(x.sql));const commit=s.calls.findIndex(x=>x.sql==='COMMIT');assert.ok(audit>0&&audit<commit);assert.match(s.calls[audit].sql,/reservation.force_allocated/);});
test('C09 expected inventory version is bound into idempotency request hash',async()=>{const first=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'s',status:'live',reservation_ttl_seconds:300}]}, {rows:[{id:'sku',available_qty:2,reserved_qty:0,version:'4'}]}, {rows:[{id:'r1',status:'active',expires_at:'2099-01-01T00:00:00Z',quantity:1}]}, {rowCount:1,rows:[{version:'5'}]}, {rowCount:1}, {rowCount:1}, {}]);const svc=new PgReservationOverrideService({pool:first.pool,clock:()=>new Date('2026-09-29T22:05:00Z')});await svc.forceAllocate(base);const hash1=first.calls.find(x=>/INSERT INTO idempotency_requests/.test(x.sql)).args[2];const second=scripted([{}, {rowCount:1,rows:[{}]}, {rows:[{id:'s',status:'live',reservation_ttl_seconds:300}]}, {rows:[{id:'sku',available_qty:2,reserved_qty:0,version:'5'}]}, {rows:[{id:'r2',status:'active',expires_at:'2099-01-01T00:00:00Z',quantity:1}]}, {rowCount:1,rows:[{version:'6'}]}, {rowCount:1}, {rowCount:1}, {}]);const svc2=new PgReservationOverrideService({pool:second.pool,clock:()=>new Date('2026-09-29T22:05:00Z')});await svc2.forceAllocate({...base,expectedInventoryVersion:5});const hash2=second.calls.find(x=>/INSERT INTO idempotency_requests/.test(x.sql)).args[2];assert.notEqual(hash1,hash2);});
