'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {normalizeAlias,PgLiveOfferService}=require('../src/services/live-offers.pg');
const {PgBuyerIntentReviewService}=require('../src/services/buyer-intent-review.pg');
const {PgWebhookHealthService}=require('../src/services/webhook-health.pg');
const {registerControlPlaneRoutes}=require('../src/routes/control-plane.routes');
function named(n){const f=async()=>{};Object.defineProperty(f,'name',{value:n});return f}
const guards={authenticate:named('authenticate'),requirePermission:p=>named(`permission_${p}`)};
test('offer aliases normalize deterministically and reject prose',()=>{assert.equal(normalizeAlias(' red-2 '),'RED-2');assert.throws(()=>normalizeAlias('red shirt'),e=>e.code==='OFFER_ALIAS_INVALID')});
test('review resolution uses stable review idempotency key',async()=>{let input,event;const pool={query:async(sql)=>{if(/SELECT id,webhook/.test(sql))return{rows:[{id:'rv',webhook_inbox_id:'in',buyer_identity_id:'b',provider_message_id:'wamid.1',status:'open'}]};if(/UPDATE buyer_intent_review/.test(sql))return{rowCount:1,rows:[{id:'rv'}]};return{rows:[]}}};const svc=new PgBuyerIntentReviewService({pool,reservation:{acceptBuyerIntent:async x=>(input=x,{outcome:'reserved',reservation:{id:'r'}})},sellerEvents:{emitFromWebhook:async x=>event=x}});const out=await svc.resolve({merchantId:'m',reviewId:'rv',sessionId:'s',inventoryVariantId:'sku',quantity:2,actorId:'op'});assert.match(input.idempotencyKey,/^review:[0-9a-f]{64}$/);assert.equal(input.providerEventId,'wamid.1');assert.equal(event.eventType,'buyer_intent.review_resolved');assert.equal(out.outcome,'resolved')});
test('webhook health maps backlog/dead-letter telemetry',async()=>{const svc=new PgWebhookHealthService({pool:{query:async()=>({rows:[{received_count:3,processing_count:2,dead_letter_count:1,processed_last_hour:8,oldest_unfinished_age_ms:'12500',last_processed_at:'2026-09-30'}]})}});assert.deepEqual(await svc.getHealth({merchantId:'m'}),{receivedCount:3,processingCount:2,deadLetterCount:1,processedLastHour:8,oldestUnfinishedAgeMs:12500,lastProcessedAt:'2026-09-30'})});
test('control-plane routes are permission partitioned',()=>{const routes=[];registerControlPlaneRoutes({route:d=>routes.push(d)},{services:{},guards});assert.equal(routes.length,7);for(const r of routes.filter(x=>x.url.includes('/offers')))assert.equal(r.preHandler[1].name,'permission_live_session.manage');for(const r of routes.filter(x=>x.url.includes('/buyer-intents/')))assert.equal(r.preHandler[1].name,'permission_buyer_intent.review');assert.equal(routes.find(x=>x.url.endsWith('/webhooks/health')).preHandler[1].name,'permission_webhook.health.read')});
